-- ДІН МЕН ДӘСТҮР — P5: fixed sequential player number.
-- Run this once in the Supabase SQL Editor, AFTER schema.sql.
--
-- Every player gets a permanent, sequential number (1, 2, 3, ...)
-- assigned by Postgres itself at insert time. It never changes after
-- that, since nothing in the app ever updates player_number again.
--
-- Registration no longer collects name/city (filled in later from
-- Settings), so new accounts insert with the column's own default
-- ('Ойыншы') for name. This trigger replaces that generic default
-- with "Ойыншы <number>" so every guest-looking account is still
-- uniquely identifiable, without ever overwriting a real chosen name.

alter table public.players
  add column if not exists player_number bigint generated by default as identity;

create unique index if not exists players_player_number_idx on public.players (player_number);

create or replace function public.set_default_player_name()
returns trigger
language plpgsql
as $$
begin
  if new.name is null or new.name = '' or new.name = 'Ойыншы' then
    new.name := 'Ойыншы ' || new.player_number;
  end if;
  return new;
end;
$$;

drop trigger if exists players_set_default_name on public.players;
create trigger players_set_default_name
  before insert on public.players
  for each row execute function public.set_default_player_name();
